USE tarrpt;

CREATE TABLE organizacao(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(64),
    segmento INT(2),
);

CREATE TABLE cliente(
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_organizacao FOREIGN KEY,
    cnpj VARCHAR(32),
    nome VARCHAR(64),
    segmento INT(2),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE rpt(
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_cliente FOREIGN KEY,
    versao INT,
    data DATE,
    hora VARCHAR(8),
    endereco VARCHAR(256),
    tela VARCHAR(64),
    nome VARCHAR(64),
    segmento INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
