CREATE DATABASE tarrpt;
USE tarrpt;

CREATE TABLE rpt(
    id INT AUTO_INCREMENT PRIMARY KEY,
    versao INT,
    cliente VARCHAR,
    data DATE,
    hora VARCHAR(8),
    endereco VARCHAR(256),
    tela VARCHAR(64),
    segmento INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE cliente(
    id INT AUTO_INCREMENT PRIMARY KEY,
    cnpj VARCHAR(32),
    nome VARCHAR(64),
    segmento INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

